name: javornik_timerush
description: Best app in the world...

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.1  # Pro inicializaci Firebase
  firebase_auth: ^5.3.4  # Pro autentifikac
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1 # Přidejte latlong2
  http: ^1.2.2
  flutter_polyline_points: ^2.1.0
  geolocator: ^13.0.2
  cloud_firestore: ^5.5.1
  gpx: ^2.3.0
  flutter_map_location_marker: ^9.1.1
  flutter_local_notifications: ^18.0.1
  flutter_background: ^1.3.0+1
  intl: ^0.20.1
  wakelock_plus: ^1.2.10
  flutter_background_service: ^5.1.0
  image_picker: ^1.0.7       # Pro výběr fotky z galerie
  firebase_storage: 12.4.10  # Pro nahrání fotky na cloud
  google_sign_in: ^6.1.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  # Pro Samsung S25 adaptivní ikona:
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  # DŮLEŽITÉ: Vygenerovat i specificky kulatou ikonu:
  icon_name: "ic_launcher"